### ISSUE TITLE
Compile under windows failed

### ISSUE THREAD

**Issue by wanglongqi** [bjodah/finitediff#7]
Compilation ends up with following error:

```
build\temp.win-amd64-2.7\Release\.\finitediff\_finitediff_templated.o:_finitedif
f_templated.cpp:(.text+0x186d3): undefined reference to `__imp_get_interval_from
_guess'
collect2.exe: error: ld returned 1 exit status
```

Mingw-user maillist has a discussion about this [http://mingw-users.1079350.n2.nabble.com/imp-prefixes-when-linking-td7386007.html](http://mingw-users.1079350.n2.nabble.com/imp-prefixes-when-linking-td7386007.htmll). I am not familiar with Cython, how can I fix this error?

**Comment by bjodah** [comment]
The link you provided seems to be broken.
Unfortunately I don't have access to a windows machine.

Could you try running the compilation with the environment variable `DISTUTILS_DEBUG` set and post the output?

**Comment by bjodah** [comment]
Ok, so I got the link working. I have an idea what might be causing this, will try to fix.

**Comment by bjodah** [comment]
@wanglongqi let me know if this work now.

**Comment by wanglongqi** [comment]
@bjodah Sorry for my late reply! I  sprained my ankle last weekend. Just come back. I tested the new repository (`Updating 6e80d1c..a6b7629`), still get the same error:`undefined reference to __imp_get_interval_from_guess`.

```
_finitediff_templated.cpp:(.text+0x186d3): undefined reference to `__imp_get_interval_from_guess'
collect2.exe: error: ld returned 1 exit status
```

I also tested under Mac OSX, gcc cannot compile .c file with `-std=c++11`, suppress that option, the repository can be compiled under Mac without problem.

**Comment by bjodah** [comment]
@wanglongqi no worries, hope your ankle heals quickly.
I googled a bit. Have you tried: `setup.py build --compiler=mingw32`?
Thanks about pointing out the `-std=c++11` flag I had forgot about it, it's now removed in the master branch.

**Comment by wanglongqi** [comment]
@bjodah Thank you! 

I think the build system should be OK. I use anaconda python distribute, they have tool chains setup.  

Following is the compile log:

```
D:\Python\MinGW\bin\gcc.exe -DMS_WIN64 -mdll -O -Wall -I.\include -I.\external\newton_interval\include -ID:\Python\lib\site-packages\numpy\core\include -ID:\Python\include -ID:\Python\PC -c .\finitediff\_finitediff_templated.cpp -o .\finitediff\_finitediff_templated.o
D:\Python\MinGW\bin\gcc.exe -DMS_WIN64 -mdll -O -Wall -I.\include -I.\external\newton_interval\include -ID:\Python\lib\site-packages\numpy\core\include -ID:\Python\include -ID:\Python\PC -c .\external\newton_interval\src\newton_interval.c -o .\external\newton_interval\src\newton_interval.o
writing .\finitediff\_finitediff_templated.def
D:\Python\MinGW\bin\g++.exe -DMS_WIN64 -shared -s .\finitediff\_finitediff_templated.o .\external\newton_interval\src\newton_interval.o .\finitediff\_finitediff_templated.def -LD:\Python\libs -LD:\Python\PCbuild\amd64 -LD:\Python\PC\VS9.0\amd64 -lpython27 -lmsvcr90 -o build\lib.win-amd64-2.7\finitediff\_finitediff_templated.pyd
```

**Comment by bjodah** [comment]
@wanglongqi I see, I'm afraid I'm out of ideas. If I get my hands on a windows machine I might try to investigate this further, but for now I'm afraid windows has to be considered as "unsupported".

**Comment by wanglongqi** [comment]
@bjodah Thanks a lot! I think I can use Mac version first.

**Comment by Chojins** [comment]
the use of __restrict__ seems to be what is breaking compilation on windows. The visual studio compilers don't support it and I think this isn't C++ standard. 

Also if __cplusplus > 199711L is likely to fail on windows as the visual studio compilers are apparently not ISO C++11 compliant.

**Comment by wanglongqi** [comment]
Thanks, Chojins. I think probably this issue can be closed for now.

**Comment by bjodah** [comment]
@Chojins thank you for your suggestions. It is true that `restrict` is not a C++ keyword. If we pass `-D__restrict__=""` it goes away though (or when using msvc set it to [__restrict](https://msdn.microsoft.com/en-us/library/5ft82fed.aspx) ). I am happy to make the `__restrict__` opt-in if that would make things simpler, i.e. something along the lines of:
```
#if defined(FINITEDIFF_WITH_RESTRICT)
  #if defined(_MSC_VER)
    #define FINITEDIFF_RESTRICT __restrict
  #else
    #define FINITEDIFF_RESTRICT __restrict__
  #endif
#else
  #define FINITEDIFF_RESTRICT
#endif

void calculate_weights(const Real_t * const FINITEDIFF_RESTRICT grid, ...
```
Then the user will be expected to pass `-DFINITEDIFF_WITH_RESTRICT` to opt in.

Regarding the `__cplusplus` macro, if it is causing trouble we can handle msvc separately.

If there is interest for windows support we could setup a appveyor config so that it gets tested continuously ([this](https://github.com/sympy/scipy-2017-codegen-tutorial/blob/master/appveyor.yml) could be a starting point). Right now, however, my time is quite limited so someone else would need to spearhead this.

@wanglongqi I'm fine with leaving this issue open until Windows is supported.
